---
- name: update homebrew
  homebrew: update_homebrew=yes

- name: add homebrew tap
  homebrew_tap: tap={{ item.name }} state=present
  with_items: "{{ homebrew_taps }}"

- name: install homebrew packages
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{ item.option | default(omit) }}
    state=upgraded
  with_items: "{{ homebrew_packages }}"

- name: install homebrew cask packages
  homebrew_cask: name={{ item.name }} state={{ item.state | default('present') }}
  #environment:
  #  HOMEBREW_CASK_OPTS: --appdir=/Applicationse
  with_items:
    - "{{ homebrew_cask_packages }}"

