---
- name: check zsh 
  shell: echo $SHELL
  register: result
  changed_when: False

- name: add zsh to /etc/shells 
  copy: src=etc/shells dest=/etc/shells mode=644
  become: yes
  when: 
    - result.stdout != "/usr/local/bin/zsh"
    - test_mode == "off"

- name: change shell to zsh
  shell: chsh -s /usr/local/bin/zsh $(whoami)
  register: result
  changed_when: "'chsh: no changes made' not in result.stderr"
  when: 
    - result.stdout != "/usr/local/bin/zsh"
    - test_mode == "off"

- name: mkdir ~/.zsh.d directory
  file: path=~/.zsh.d state=directory

- name: install zplug 
  stat: path=~/.zplug 
  register: result
- shell: curl -sL zplug.sh/installer | zsh 
  when: not result.stat.exists

- name: get dircolor solarized  
  file: path=~/.config/solarized state=directory
- get_url: >
    url=https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.256dark
    dest=~/.config/solarized/dircolors.256dark
    force=True

- name: mkdir dotifles directory
  file: >
    path={{ item.dest }}
    state=directory
    mode={{ item.dest_mode | default("0755") }}
    force=yes
  with_items: "{{ dotfiles }}"
  when: item.src | search("\/")

- name: setup dotfiles
  copy: >
    src={{ item.src }}
    dest={{ item.dest | default("~") }}
    mode={{ item.mode | default("0644") }}
    backup={{ item.backup | default("no") }}
    force=yes
  with_items: "{{ dotfiles }}"
