os: osx
osx_image: xcode8.2
language: bash
sudo: required
install:
    - sudo apt-get install python-pip
    - sudo pip install ansible
script:
    - bash install --tags dirs 
    - bash install --tags homebrew
