os: osx
osx_image: xcode8.2
language: bash
install:
    - brew install ansible
script:
    - bash -n install
    - ansible-playbook ansible/site.yml --syntax-check
    - ansible-playbook ansible/site.yml --extra-vars "test_mode=on"
