---
- name: Dock To right the position of the Dock
  osx_defaults: domain=com.apple.dock key=orientation type=string value=right

# TODO:
## dockを最小にする
## dockは稼働中アプリ以外表示しない
## ctrl+tackpadで、拡大・縮小
## プリンタ設定
## wifi設定
## iterm2の設定
## alfredの設定
## chromeログイン
## dashの設定
## docker for macの設定
## clipyの設定
## caffeinの設定

