---
atom_packages:
  - name: solarized-dark-ui
  - name: tree-view-git-status
  - name: file-icons
  - name: tablr
  - name: color-picker
  - name: vim-mode-plus
  - name: vim-mode-plus-ex-mode
  - name: vim-mode-plus-project-find-from-search
  - name: linter
  - name: autocomplete
  - name: autocomplete-paths
  - name: python-tools
  - name: autocomplete-python
  - name: go-plus
  - name: autocomplete-go
  - name: environment
  - name: highlight-selected
