---
- name: add zsh to /etc/shells 
  copy: src=etc/shells dest=/etc/shells mode=644
  become: yes

- name: change shell to zsh
  shell: chsh -s /usr/local/bin/zsh $(whoami)
  register: result
  changed_when: "'chsh: no changes made' not in result.stderr"
  become: yes

- name: install zplug 
  shell: curl -sL zplug.sh/installer | zsh 
  ignore_errors: True

- name: install dein.vim
  file: path={{ deinvim['dir'] }} state=directory
- get_url: >
    url=https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/{{ deinvim['shell'] }}
    dest={{ deinvim['dir'] }}/{{ deinvim['shell'] }}
    force=True
    mode=u+x
- shell: "./{{ deinvim['shell'] }} {{ deinvim['dir'] }}/"
  args:
    chdir: "{{ deinvim['dir'] }}/"
  register: result
  changed_when: "'already exists!' not in result.stdout"

- name: mkdir dotifles directory
  file: >
    path={{ item.dest }}
    state=directory
    mode={{ item.dest_mode | default('0755') }}
    force=yes
  with_items: "{{ dotfiles }}"
  when: item.src | search("\/")

- name: setup dotfiles
  copy: >
    src={{ item.src }}
    dest={{ item.dest | default('~') }}
    mode={{ item.mode | default('0644') }}
    backup={{ item.backup | default('no') }}
    force=yes
  with_items: "{{ dotfiles }}"
  notify: source zshrc 

