---
- name: Install homebrew packages
  homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state | default('latest') }}"
      install_options: "{{ item.option | default(omit) }}"
      state: upgraded
  with_items: "{{ homebrew_packages }}"

- name: Setting ghq config 
  git_config: name=ghq.root scope=global value="~/src"
