---
- name: Install go packages 
  shell: go get github.com/mattn/memo
  environment: 
    GOPATH: "{{ lookup('env', 'HOME') }}"

- name: Setup files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    backup: "{{ item.backup | default('no') }}"
    force: yes
  with_items: "{{ files }}"

- name: Install zsh completion
  get_url:
    url: https://raw.githubusercontent.com/mattn/memo/master/misc/completion.zsh
    dest: ~/.zsh.d/memo_completion.sh 
    mode: 0644 

- name: Setup Dropbox Symbolic link 
  file:
    src: ~/.config/memo/_posts
    dest: ~/Dropbox/memo 
    state: link

- name: Setup git remote origin url
  git_config:
    name: remote.origin.url
    scope: local 
    value: git@github.com:humangas/memo.git
