memodir = "~/.config/memo/_posts"
editor = "vim"
column = 20
selectcmd = "fzf"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
assetsdir = "."
pluginsdir = "~/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
