---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: homebrew,     tags: ['homebrew'] }
    - { role: dotfiles,     tags: ['dotfiles'] }
    - { role: atom,         tags: ['atom'] }
    - { role: osx_defaults, tags: ['osx_defaults'] }
