---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: homebrew,     tags: ['homebrew'] }
    - { role: dirs,         tags: ['dotfiles', 'dirs'] }
    - { role: zsh,          tags: ['dotfiles', 'zsh'] }
    - { role: ssh,          tags: ['dotfiles', 'ssh'] }
    - { role: tmux,         tags: ['dotfiles', 'tmux'] }
    - { role: vim,          tags: ['dotfiles', 'vim'] }
    - { role: ghq,          tags: ['dotfiles', 'ghq'] }
    - { role: macos_dock,   tags: ['macos'   , 'dock'] }
    - { role: atom,         tags: ['atom'] }
