---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: homebrew,     tags: ['homebrew'        ] }
    - { role: dirs,         tags: ['dotfiles', 'dirs'] }
    - { role: zsh,          tags: ['dotfiles', 'zsh' ] }
    - { role: tmux,         tags: ['dotfiles', 'tmux'] }
    - { role: vim,          tags: ['dotfiles', 'vim' ] }
    - { role: ssh,          tags: ['dotfiles', 'ssh' ] }
    - { role: ghq,          tags: ['dotfiles', 'ghq' ] }
    - { role: pip,          tags: ['pip'             ] }
    - { role: gem,          tags: ['gem'             ] }
    - { role: npm,          tags: ['npm'             ] }
    - { role: macos_dock,   tags: ['macos'   , 'dock'] }
