---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: homebrew,     tags: ['homebrew'         ] }
    - { role: dirs,         tags: ['dotfiles', 'dirs' ] }
    - { role: zsh,          tags: ['dotfiles', 'zsh'  ] }
    - { role: tmux,         tags: ['dotfiles', 'tmux' ] }
    - { role: vim,          tags: ['dotfiles', 'vim'  ] }
    - { role: ssh,          tags: ['dotfiles', 'ssh'  ] }
    - { role: go,           tags: ['go'               ] }
    - { role: pip,          tags: ['pip'              ] }
    - { role: gem,          tags: ['gem'              ] }
    - { role: npm,          tags: ['npm'              ] }
    - { role: tig,          tags: ['tool'    , 'tig'  ] }
    - { role: tool_ghq,     tags: ['tool'    , 'ghq'  ] }
    - { role: tool_memo,    tags: ['tool'    , 'memo' ] }
    - { role: macos_dock,   tags: ['macos'   , 'dock' ] }
